// ═══════════════════════════════════════════════════════════
//  RentVerify — Dummy Data
//  Edit this file to add/remove agents and listings without
//  touching the main app logic in index.html
// ═══════════════════════════════════════════════════════════

// ── Stock images (Unsplash) ──────────────────────────────
const IMGS = [
  "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&h=280&fit=crop&auto=format&q=80",   // 0  white bedroom
  "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=280&fit=crop&auto=format&q=80",   // 1  modern living room
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=500&h=280&fit=crop&auto=format&q=80", // 2  studio apartment
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&h=280&fit=crop&auto=format&q=80", // 3  bright bedroom
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=280&fit=crop&auto=format&q=80", // 4  warm bedroom
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=500&h=280&fit=crop&auto=format&q=80", // 5  kitchen/dining
  "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=500&h=280&fit=crop&auto=format&q=80", // 6  minimal bedroom
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=500&h=280&fit=crop&auto=format&q=80",   // 7  window room
  "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=500&h=280&fit=crop&auto=format&q=80", // 8  modern bedroom
  "https://images.unsplash.com/photo-1586023492125-27b2c045efd3?w=500&h=280&fit=crop&auto=format&q=80", // 9  furnished room
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=500&h=280&fit=crop&auto=format&q=80", // 10 apartment building
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=500&h=280&fit=crop&auto=format&q=80",   // 11 condo exterior
  "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=500&h=280&fit=crop&auto=format&q=80", // 12 apartment living
  "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&h=280&fit=crop&auto=format&q=80",   // 13 cozy room
  "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=500&h=280&fit=crop&auto=format&q=80", // 14 studio living
];

// ── Agents ───────────────────────────────────────────────
const AGENTS = [
  {
    name: "Ahmad Hafiz",
    initials: "AH",
    sub: "UTM Skudai Specialist · 12 yrs exp",
    color: "#5B5BD6",
    about: "Ahmad has been serving UTM students for over 12 years. He specialises in studio and master room rentals within walking distance of the UTM campus, and handles all paperwork digitally.",
    license: "LPPEH/E(3)/0247 — Registered since 2012",
    stats: ["0", "4.9 ★", "< 2 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "Siti Rahimah",
    initials: "SR",
    sub: "Female Housing Specialist · 8 yrs exp",
    color: "#8B5CF6",
    about: "Siti focuses on verified female-only and mixed housing in Skudai and Gelang Patah, ensuring safe and comfortable environments. All her listings include utility breakdowns.",
    license: "LPPEH/E(3)/0481 — Registered since 2016",
    stats: ["0", "4.7 ★", "< 3 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "Mohd Faizal",
    initials: "MF",
    sub: "Premium Listings · 6 yrs exp",
    color: "#EC4899",
    about: "Mohd Faizal specialises in premium condominiums and studio apartments with full amenities including pool and gym. Best choice for students seeking a higher comfort level.",
    license: "LPPEH/E(3)/0612 — Registered since 2018",
    stats: ["0", "4.8 ★", "< 4 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "Lee Wei Xian",
    initials: "LW",
    sub: "Budget & Mid-Range · 5 yrs exp",
    color: "#0EA5E9",
    about: "Lee specialises in budget-friendly options for students on tight budgets. All listings are competitively priced with transparent, no-hidden-fee pricing.",
    license: "LPPEH/E(3)/0704 — Registered since 2019",
    stats: ["0", "4.3 ★", "< 6 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "Nurul Ain",
    initials: "NA",
    sub: "Nusajaya & JB Central · 7 yrs exp",
    color: "#F97316",
    about: "Nurul Ain covers Nusajaya, Bukit Indah, and Johor Bahru City Centre — ideal for students doing internships or seeking cheaper rooms with good MRT access.",
    license: "LPPEH/E(3)/0558 — Registered since 2017",
    stats: ["0", "4.6 ★", "< 3 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "David Lim",
    initials: "DL",
    sub: "JB City Specialist · 10 yrs exp",
    color: "#10B981",
    about: "David manages premium and mid-range properties in downtown Johor Bahru, close to business districts, shopping centres, and the Causeway — great for students with city internships.",
    license: "LPPEH/E(3)/0322 — Registered since 2014",
    stats: ["0", "4.5 ★", "< 5 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  },
  {
    name: "Priya Ramasamy",
    initials: "PR",
    sub: "Pulai & Tampoi Corridor · 4 yrs exp",
    color: "#EF4444",
    about: "Priya serves the Pulai and Tampoi corridor, offering a mix of affordable and mid-range listings with strong highway connectivity. Particularly active in female-friendly housing.",
    license: "LPPEH/E(3)/0891 — Registered since 2020",
    stats: ["0", "4.4 ★", "< 4 hrs"],
    statLabels: ["Listings", "Rating", "Response"]
  }
];

// ── Listings ─────────────────────────────────────────────
// listingVerified: true  = physically inspected by RentVerify team
// listingVerified: false = agent-submitted, not yet inspected
// dist: descriptive proximity label shown on cards
// img: IMGS[index] or null (falls back to gradient + emoji)
const LISTINGS = [

  // ════ VERIFIED — NEAR UTM (walking distance < 10 min) ════
  {
    id: 0,
    title: "Cosy studio, 5-min walk to UTM main gate",
    loc: "Taman Universiti, Skudai",
    price: "RM 720",
    priceNum: 720,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "5 min walk",
    rating: "4.9",
    reviews: 27,
    agentIdx: 0,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#C7D2FE,#A5B4FC)",
    emoji: "🏠",
    img: IMGS[0],
    features: ["🛋 Fully furnished", "📶 WiFi included", "❄️ Air-con", "🚿 Private bathroom"],
  },
  {
    id: 1,
    title: "Single room with study desk, steps from UTM hostel",
    loc: "Jalan Universiti, Skudai",
    price: "RM 520",
    priceNum: 520,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "3 min walk",
    rating: "4.6",
    reviews: 18,
    agentIdx: 0,
    listingVerified: true,
    avail: "2 slots left",
    color: "linear-gradient(135deg,#DDD6FE,#C4B5FD)",
    emoji: "🏘",
    img: IMGS[3],
    features: ["📚 Study desk", "❄️ Air-con", "🪟 Window room", "📶 WiFi"],
  },
  {
    id: 2,
    title: "Master bedroom, ensuite bathroom, UTM walking zone",
    loc: "Taman Universiti, Skudai",
    price: "RM 850",
    priceNum: 850,
    type: "Master room",
    furnish: "Fully furnished",
    dist: "7 min walk",
    rating: "4.8",
    reviews: 21,
    agentIdx: 1,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FBCFE8,#F9A8D4)",
    emoji: "🛏",
    img: IMGS[4],
    features: ["🚿 Ensuite bathroom", "🛋 Fully furnished", "❄️ Air-con", "📶 500 Mbps WiFi"],
  },
  {
    id: 3,
    title: "Female-only room, walking distance to UTM Faculty of Computing",
    loc: "Jalan Universiti, Skudai",
    price: "RM 550",
    priceNum: 550,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "8 min walk",
    rating: "4.7",
    reviews: 15,
    agentIdx: 1,
    listingVerified: true,
    avail: "1 slot left",
    color: "linear-gradient(135deg,#FDE68A,#FCD34D)",
    emoji: "🏠",
    img: IMGS[13],
    features: ["👩 Female tenants only", "🛋 Furnished", "🧺 Washer provided", "📶 WiFi"],
  },
  {
    id: 4,
    title: "Bright studio with separate kitchen, near UTM clinic",
    loc: "Taman Perling, Skudai",
    price: "RM 780",
    priceNum: 780,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "9 min walk",
    rating: "4.5",
    reviews: 12,
    agentIdx: 0,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#BAE6FD,#7DD3FC)",
    emoji: "🏗",
    img: IMGS[14],
    features: ["🍳 Separate kitchen", "🛋 Fully furnished", "❄️ Air-con", "🅿️ Parking"],
  },

  // ════ VERIFIED — MID-RANGE (bus or 10–25 min walk) ════
  {
    id: 5,
    title: "Single room with AC, walking distance to UTM",
    loc: "Gelang Patah, JB",
    price: "RM 580",
    priceNum: 580,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "12 min bus",
    rating: "4.2",
    reviews: 11,
    agentIdx: 1,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#D1FAE5,#A7F3D0)",
    emoji: "🏘",
    img: IMGS[7],
    features: ["❄️ Air-con", "🪟 Window room", "🧺 Shared laundry", "📶 WiFi"],
  },
  {
    id: 6,
    title: "Master bedroom, full furnish + WiFi included",
    loc: "Pulai, Johor",
    price: "RM 850",
    priceNum: 850,
    type: "Master room",
    furnish: "Fully furnished",
    dist: "15 min car",
    rating: "4.8",
    reviews: 19,
    agentIdx: 2,
    listingVerified: true,
    avail: "1 slot left",
    color: "linear-gradient(135deg,#FCE7F3,#FBCFE8)",
    emoji: "🛏",
    img: IMGS[8],
    features: ["🛋 Fully furnished", "🚿 Private bathroom", "🅿️ Parking", "📶 WiFi"],
  },
  {
    id: 7,
    title: "Affordable single room, 10 min to UTM by bus",
    loc: "Skudai Town",
    price: "RM 630",
    priceNum: 630,
    type: "Single room",
    furnish: "Semi-furnished",
    dist: "10 min bus",
    rating: "4.0",
    reviews: 8,
    agentIdx: 3,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FEF3C7,#FDE68A)",
    emoji: "🏢",
    img: IMGS[9],
    features: ["🛋 Semi-furnished", "🚌 Bus stop 2 min", "❄️ Air-con"],
  },
  {
    id: 8,
    title: "Budget shared room, clean and near UTM",
    loc: "Skudai, JB",
    price: "RM 450",
    priceNum: 450,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "10 min bus",
    rating: "3.8",
    reviews: 6,
    agentIdx: 1,
    listingVerified: true,
    avail: "3 slots left",
    color: "linear-gradient(135deg,#E0E7FF,#C7D2FE)",
    emoji: "🏠",
    img: IMGS[6],
    features: ["🛋 Furnished", "🧺 Shared laundry", "📶 WiFi", "💰 Bills included"],
  },
  {
    id: 9,
    title: "Studio unit near Gelang Patah interchange",
    loc: "Gelang Patah, JB",
    price: "RM 680",
    priceNum: 680,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "15 min car",
    rating: "4.5",
    reviews: 14,
    agentIdx: 0,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#DBEAFE,#BFDBFE)",
    emoji: "🏗",
    img: IMGS[2],
    features: ["🛋 Fully furnished", "❄️ Air-con", "🅿️ Parking", "📶 WiFi"],
  },
  {
    id: 10,
    title: "Spacious master room, 7 min drive to UTM",
    loc: "Taman Universiti, JB",
    price: "RM 800",
    priceNum: 800,
    type: "Master room",
    furnish: "Fully furnished",
    dist: "10 min bus",
    rating: "4.7",
    reviews: 31,
    agentIdx: 0,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#CFFAFE,#A5F3FC)",
    emoji: "🏡",
    img: IMGS[1],
    features: ["🛋 Fully furnished", "🚿 Attached bathroom", "📶 500 Mbps WiFi", "🛡 CCTV"],
  },
  {
    id: 11,
    title: "Female-only house, single room, near UTM faculty block",
    loc: "Skudai, JB",
    price: "RM 550",
    priceNum: 550,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "12 min bus",
    rating: "4.6",
    reviews: 17,
    agentIdx: 1,
    listingVerified: true,
    avail: "2 slots left",
    color: "linear-gradient(135deg,#FDF4FF,#FAE8FF)",
    emoji: "🏠",
    img: IMGS[13],
    features: ["👩 Female tenants only", "🛋 Fully furnished", "🧺 Washer provided", "📶 WiFi"],
  },
  {
    id: 12,
    title: "Whole unit (3 rooms) — ideal for 3 UTM students co-renting",
    loc: "Skudai Town",
    price: "RM 1,400",
    priceNum: 1400,
    type: "Whole unit",
    furnish: "Fully furnished",
    dist: "10 min bus",
    rating: "4.3",
    reviews: 7,
    agentIdx: 0,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#ECFDF5,#D1FAE5)",
    emoji: "🏡",
    img: IMGS[12],
    features: ["🏠 3 bedrooms", "🛋 Fully furnished", "🅿️ 2 parking spots", "🧺 Washer & dryer"],
  },
  {
    id: 13,
    title: "Single room, female-only house near UTM clinic",
    loc: "Nusajaya, Skudai",
    price: "RM 600",
    priceNum: 600,
    type: "Single room",
    furnish: "Fully furnished",
    dist: "5 min walk",
    rating: "4.8",
    reviews: 28,
    agentIdx: 1,
    listingVerified: true,
    avail: "1 slot left",
    color: "linear-gradient(135deg,#FFF7ED,#FED7AA)",
    emoji: "🏠",
    img: IMGS[3],
    features: ["👩 Female only", "🛋 Fully furnished", "🧴 Clean bathroom", "📶 WiFi"],
  },

  // ════ VERIFIED — FAR FROM UTM (car needed, 25–40 min) ════
  {
    id: 14,
    title: "New studio, Sutera Utama — gated compound, pool access",
    loc: "Sutera Utama, Skudai",
    price: "RM 950",
    priceNum: 950,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "25 min car",
    rating: "4.9",
    reviews: 9,
    agentIdx: 2,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#EDE9FE,#DDD6FE)",
    emoji: "🏢",
    img: IMGS[11],
    features: ["🛡 Gated & guarded", "🛋 Brand new furniture", "🅿️ Covered parking", "🏊 Pool access"],
  },
  {
    id: 15,
    title: "Master room with study desk, Pulai Springs area",
    loc: "Pulai, Johor",
    price: "RM 780",
    priceNum: 780,
    type: "Master room",
    furnish: "Fully furnished",
    dist: "20 min car",
    rating: "4.4",
    reviews: 22,
    agentIdx: 2,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FCE7F3,#FBCFE8)",
    emoji: "🛏",
    img: IMGS[4],
    features: ["📚 Study desk & chair", "🛋 Fully furnished", "❄️ Air-con", "📶 WiFi"],
  },
  {
    id: 16,
    title: "Compact studio, near KPJ Johor Specialist Hospital",
    loc: "Tampoi, JB",
    price: "RM 750",
    priceNum: 750,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "20 min bus",
    rating: "4.2",
    reviews: 10,
    agentIdx: 6,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FEE2E2,#FECACA)",
    emoji: "🏢",
    img: IMGS[0],
    features: ["🛋 Fully furnished", "❄️ Air-con", "🅿️ Free parking", "📶 Fibre WiFi"],
  },
  {
    id: 17,
    title: "Single room, 5 min walk to UTM bus terminal",
    loc: "Gelang Patah, JB",
    price: "RM 520",
    priceNum: 520,
    type: "Single room",
    furnish: "Semi-furnished",
    dist: "5 min walk",
    rating: "4.1",
    reviews: 13,
    agentIdx: 3,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#F0FDF4,#DCFCE7)",
    emoji: "🏘",
    img: IMGS[6],
    features: ["🚌 UTM bus terminal 5 min", "❄️ Air-con", "🪟 Bright window"],
  },
  {
    id: 18,
    title: "Premium condo studio — gym, pool, security 24/7",
    loc: "Bukit Indah, JB",
    price: "RM 1,100",
    priceNum: 1100,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "30 min car",
    rating: "4.8",
    reviews: 34,
    agentIdx: 4,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FFF7ED,#FFEDD5)",
    emoji: "🏢",
    img: IMGS[10],
    features: ["🏋 Gym access", "🏊 Swimming pool", "🛡 24-hr security", "🅿️ Covered parking"],
  },
  {
    id: 19,
    title: "Whole unit 3BR near Bukit Indah Aeon Mall",
    loc: "Bukit Indah, JB",
    price: "RM 1,600",
    priceNum: 1600,
    type: "Whole unit",
    furnish: "Fully furnished",
    dist: "30 min car",
    rating: "4.5",
    reviews: 11,
    agentIdx: 4,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#ECFDF5,#D1FAE5)",
    emoji: "🏡",
    img: IMGS[12],
    features: ["🏠 3 bedrooms", "🛋 Fully furnished", "🛒 Mall nearby", "🅿️ 2 parking spots"],
  },

  // ════ VERIFIED — DOWNTOWN JB (35–50 min, great for internships) ════
  {
    id: 20,
    title: "Studio in JB City Centre — best for internship students",
    loc: "Johor Bahru City, JB",
    price: "RM 1,150",
    priceNum: 1150,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "40 min by MRT",
    rating: "4.7",
    reviews: 19,
    agentIdx: 5,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#DCFCE7,#BBF7D0)",
    emoji: "🏙",
    img: IMGS[14],
    features: ["🚇 MRT station nearby", "🛋 Fully furnished", "🏙 City view", "📶 Fibre WiFi"],
  },
  {
    id: 21,
    title: "Master room near Komtar JBCC, MRT accessible",
    loc: "Bukit Chagar, JB",
    price: "RM 950",
    priceNum: 950,
    type: "Master room",
    furnish: "Fully furnished",
    dist: "35 min by MRT",
    rating: "4.4",
    reviews: 8,
    agentIdx: 5,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#F0FDF4,#DCFCE7)",
    emoji: "🏢",
    img: IMGS[1],
    features: ["🚇 5 min to MRT", "🛋 Fully furnished", "❄️ Air-con", "🏪 Mall nearby"],
  },
  {
    id: 22,
    title: "Affordable single room, Larkin area, bus to UTM",
    loc: "Larkin, JB",
    price: "RM 700",
    priceNum: 700,
    type: "Single room",
    furnish: "Semi-furnished",
    dist: "35 min by bus",
    rating: "4.0",
    reviews: 6,
    agentIdx: 4,
    listingVerified: true,
    avail: "Available now",
    color: "linear-gradient(135deg,#FFFBEB,#FEF3C7)",
    emoji: "🏠",
    img: IMGS[7],
    features: ["🚌 Bus terminal nearby", "🛋 Semi-furnished", "❄️ Air-con"],
  },

  // ════ UNVERIFIED — agent-submitted, not physically inspected ════
  {
    id: 23,
    title: "Master room near UTM hostel block (unconfirmed photos)",
    loc: "Gelang Patah, JB",
    price: "RM 680",
    priceNum: 680,
    type: "Master room",
    furnish: "Partially furnished",
    dist: "10 min bus",
    rating: "3.1",
    reviews: 5,
    agentIdx: 1,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#E8E8E5,#D8D8D4)",
    emoji: "🏘",
    img: null,
    features: ["🛋 Partial furnish", "🚌 Bus nearby"],
  },
  {
    id: 24,
    title: "Small single room — own bathroom claimed by agent",
    loc: "Tampoi, JB",
    price: "RM 550",
    priceNum: 550,
    type: "Single room",
    furnish: "Unfurnished",
    dist: "15 min car",
    rating: "2.4",
    reviews: 3,
    agentIdx: 3,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#DDDBD6,#CECCC6)",
    emoji: "🏠",
    img: null,
    features: ["Unfurnished", "🚗 Car needed"],
  },
  {
    id: 25,
    title: "Whole unit 3-bedroom — photos may not be current",
    loc: "Pulai, Johor",
    price: "RM 1,600",
    priceNum: 1600,
    type: "Whole unit",
    furnish: "Fully furnished",
    dist: "20 min car",
    rating: "3.6",
    reviews: 4,
    agentIdx: 2,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#E2DCCC,#D0C8B4)",
    emoji: "🏡",
    img: null,
    features: ["🛋 Claimed fully furnished", "🅿️ Parking", "3 bedrooms"],
  },
  {
    id: 26,
    title: "Single room, Skudai Parade area (details unverified)",
    loc: "Skudai Town",
    price: "RM 490",
    priceNum: 490,
    type: "Single room",
    furnish: "Semi-furnished",
    dist: "10 min bus",
    rating: "2.8",
    reviews: 2,
    agentIdx: 0,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#E4E0D8,#D4CECC)",
    emoji: "🏘",
    img: null,
    features: ["🛋 Semi-furnished (claimed)", "🚌 Bus access"],
  },
  {
    id: 27,
    title: "Studio near Bukit Indah — agent photos, not inspected",
    loc: "Bukit Indah, JB",
    price: "RM 850",
    priceNum: 850,
    type: "Studio",
    furnish: "Fully furnished",
    dist: "30 min car",
    rating: "3.3",
    reviews: 4,
    agentIdx: 4,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#FEF9C3,#FEF08A)",
    emoji: "🏢",
    img: null,
    features: ["🛋 Claimed furnished", "❄️ Air-con (claimed)"],
  },
  {
    id: 28,
    title: "Single room in Larkin — no recent photos on file",
    loc: "Larkin, JB",
    price: "RM 650",
    priceNum: 650,
    type: "Single room",
    furnish: "Semi-furnished",
    dist: "35 min bus",
    rating: "2.6",
    reviews: 3,
    agentIdx: 5,
    listingVerified: false,
    avail: "Available",
    color: "linear-gradient(135deg,#E7E5E4,#D6D3D1)",
    emoji: "🏠",
    img: null,
    features: ["🛋 Semi-furnished (claimed)", "📶 WiFi (claimed)"],
  },
];
